# Generated by Django 6.0.1 on 2026-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclevalue',
            name='market_value',
            field=models.PositiveIntegerField(),
        ),
    ]
