# Generated by Django 6.0.1 on 2026-04-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_claimimage_damagereport_insuranceclaim_usercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageanalysis',
            name='agent_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damageanalysis',
            name='appeal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='damageanalysis',
            name='user_appeal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_admin.damageanalysis'),
        ),
    ]
