# Generated by Django 6.0.1 on 2026-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_damageanalysis_agent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
