# Generated by Django 6.0.3 on 2026-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0004_damageanalysis_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageanalysis',
            name='detected_parts',
            field=models.TextField(blank=True, help_text='e.g., Bumper: 0.05, Hood: 0.10', null=True),
        ),
        migrations.AddField(
            model_name='damageanalysis',
            name='total_damage_factor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='damageanalysis',
            name='yolo_output_image',
            field=models.ImageField(blank=True, null=True, upload_to='yolo_results/'),
        ),
    ]
