# Generated by Django 6.0.3 on 2026-04-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0006_damageanalysis_ai_raw_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='usercomplaint',
            name='user',
        ),
        migrations.RenameField(
            model_name='damageanalysis',
            old_name='date_analyzed',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='claimimage',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='damageanalysis',
            name='ai_raw_results',
        ),
        migrations.RemoveField(
            model_name='damageanalysis',
            name='damage_level',
        ),
        migrations.RemoveField(
            model_name='damageanalysis',
            name='detected_parts',
        ),
        migrations.RemoveField(
            model_name='damageanalysis',
            name='total_damage_factor',
        ),
        migrations.RemoveField(
            model_name='damageanalysis',
            name='yolo_output_image',
        ),
        migrations.AlterField(
            model_name='claimimage',
            name='image',
            field=models.ImageField(upload_to='damage_scans/'),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='estimated_claim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='major_coeff',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='minor_coeff',
            field=models.FloatField(default=0.025),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='moderate_coeff',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='damageanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Agent', 'Agent'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclevalue',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='DamageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('box_coords', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='my_admin.damageanalysis')),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin.claimimage')),
            ],
        ),
        migrations.DeleteModel(
            name='DamageReport',
        ),
        migrations.DeleteModel(
            name='InsuranceClaim',
        ),
        migrations.DeleteModel(
            name='InsuranceCompany',
        ),
        migrations.DeleteModel(
            name='UserComplaint',
        ),
    ]
