# Generated by Django 6.0.3 on 2026-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0008_usercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageanalysis',
            name='damage_level',
            field=models.CharField(default='TBD', max_length=20),
        ),
        migrations.AddField(
            model_name='damageanalysis',
            name='total_damage_factor',
            field=models.FloatField(default=0.0),
        ),
    ]
