# Generated by Django 6.0.3 on 2026-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0009_damageanalysis_damage_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageanalysis',
            name='detected_parts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
