# Generated by Django 6.0.3 on 2026-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0010_damageanalysis_detected_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
